In [2]:
import numpy as np

In [6]:
arr=np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
a=[1, 2, 3, 4, 5, 6, 7,"hello"]
a

[1, 2, 3, 4, 5, 6, 7, 'hello']

In [8]:
np.array(a)

array(['1', '2', '3', '4', '5', '6', '7', 'hello'], dtype='<U21')

In [9]:
a=[1, 2, 3, 4, 5, 6, 7,3.5]
np.array(a)


array([1. , 2. , 3. , 4. , 5. , 6. , 7. , 3.5])

In [10]:
L=[[1,2,3],[4,5,6],[7,8,9]]
L

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(L)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [16]:
arr=np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
arr=np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [22]:
arr=np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [23]:
arr=np.linspace(1,5,100)
arr

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [92]:
np.random.rand(10)

array([0.52936391, 0.91384941, 0.48656457, 0.01671425, 0.26997476,
       0.66708591, 0.22153865, 0.08635159, 0.28211377, 0.53937769])

In [110]:
np.random.randn(10)

array([ 1.76919953, -1.86719393, -0.71835888,  1.70243606,  1.06746637,
        2.06443344,  0.43774052,  0.45099563, -0.95353555,  2.17250007])

In [178]:
np.random.randint(10,20,10)

array([15, 16, 15, 18, 10, 16, 16, 15, 19, 11], dtype=int32)

In [182]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [183]:
arr.shape

(3, 3)

In [184]:
arr.size

9

In [185]:
arr.dtype

dtype('int64')

In [187]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [191]:
x=arr.min()
x

np.int64(1)

In [194]:
arr.max()

np.int64(9)

In [195]:
arr.sum()

np.int64(45)

In [196]:
np.sum(arr,axis=0) 

array([12, 15, 18])

In [197]:
np.sum(arr,axis=1) 

array([ 6, 15, 24])

In [198]:
arr.mean()

np.float64(5.0)

In [199]:
arr.std()

np.float64(2.581988897471611)

In [200]:
arr.argmax()

np.int64(8)

In [201]:
arr.argmin()

np.int64(0)

In [208]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [209]:
arr.reshape(6,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])