In [3]:
import numpy as np

## Array Operations

Arithmetic Operation

In [ ]:
a1=np.array([1,2,3,4,5])      ## Size of array must be same
a2=np.array([6,7,8,9,10])

In [6]:
a = a1 + a2
a

array([ 7,  9, 11, 13, 15])

In [7]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [8]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [9]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [10]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [48]:
a1 // a2
a

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

Broadcasting

In [ ]:
l=[10,20,30,40]  ##In list you have if you wanted to add 10 in all the elements then you have to loop it over then add 10 and the append arrays do this in one go
arr=np.array(l)

In [13]:
arr + 10

array([20, 30, 40, 50])

In [44]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [45]:
a=a+10
a

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

Deep and Shallow copy

In [61]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [62]:
slice=a[:5]
slice

array([1, 2, 3, 4, 5])

In [ ]:
slice+=10
slice

Matrix operation

In [64]:
A=np.arange(1,5).reshape(2,2)
B=np.arange(6,10).reshape(2,2)


In [65]:
A

array([[1, 2],
       [3, 4]])

In [66]:
B

array([[6, 7],
       [8, 9]])

In [67]:
A @ B

array([[22, 25],
       [50, 57]])

In [68]:
np.dot(A,B)

array([[22, 25],
       [50, 57]])

In [69]:
A.T

array([[1, 3],
       [2, 4]])

## Advance Array Manipulation

Stacking Array

In [70]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [71]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [72]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [76]:
## In this you can only use array not the matrix

Spliting Array

In [77]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [81]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [82]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [83]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]