In [1]:
import numpy as np

## Numpy Indexing And Slicing Of Vector

In [3]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
arr[6]

np.int64(17)

In [18]:
print(arr[1:5])
print(arr[:5])
print(arr[1:])
print(arr[1:5:2])
print(arr[::-1])

[12 13 14 15]
[11 12 13 14 15]
[12 13 14 15 16 17 18 19 20]
[12 14]
[20 19 18 17 16 15 14 13 12 11]


## Numpy Indexing And Slicing Of Marix

In [19]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [22]:
print(arr[3])
print(arr[4])
print(arr[4,2])
print(arr[0,0])


[16 17 18 19 20]
[21 22 23 24 25]
23
1


In [ ]:
## Whta if you want the matrix of 2,3 and 7,8

slice=arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [28]:
## Slice 19,29 and 24,25 and 29,30

slice=arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [29]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

## Boolean Indexing

In [41]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [42]:
bool_index= arr %2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [43]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])